In [ ]:
!pip install -q google-generativeai pandas tqdm

In [ ]:
import pandas as pd
import json
import time

from tqdm import tqdm

from openai import OpenAI

In [ ]:
from openai import OpenAI

API_KEY = "some_api_key"

client = OpenAI(
    api_key=API_KEY,
    base_url="https://api.groq.com/openai/v1"
)

In [ ]:
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
        {
            "role": "user",
            "content": "Say hello in one sentence."
        }
    ]
)

print(response.choices[0].message.content)

Hello, how can I assist you today?

In [ ]:
print(API_KEY[:10])

gsk_uQaasW

In [ ]:
df = pd.read_csv("/content/text_asr.csv")

df.head()

,complaint_id,asr_attempt_id,text_raw,asr_lang,is_primary,transcript_ts,asr_model_version
0,PGR202500001,1,"Namaste, for the past three days. We are exper...",mr,True,2025-02-14 09:18:54,asr_mr_v3
1,PGR202500002,1,"Ji, for the past three days. I am reporting th...",mr,True,2025-05-28 02:15:39,asr_mr_v3
2,PGR202500003,1,"Good evening, for 48 hours. We are experiencin...",hi,True,2025-05-10 04:28:36,asr_hi_v3
3,PGR202500004,1,"Good evening, since last night. an old buildin...",mr,True,2025-04-07 19:58:15,asr_mr_v3
4,PGR202500005,1,"Hi, for the past three days. We are experienci...",hi,True,2025-04-06 22:51:29,asr_hi_v3

In [ ]:
if "is_primary" in df.columns:
    df = df[df["is_primary"] == True]

df = df[
    [
        "complaint_id",
        "text_raw"
    ]
]

df = df.drop_duplicates("complaint_id")

df.reset_index(drop=True, inplace=True)

print(df.shape)

(900, 2)

In [ ]:
SYSTEM_PROMPT = """
You are an experienced municipal grievance officer.

You are given ONE civic complaint.

Your task is to assess its severity.

Evaluate ONLY using the complaint text.

Do not assume information that is not explicitly mentioned.

Assign:

1. severity_score (0-10)

2. severity_label

Possible labels:

LOW
MEDIUM
HIGH
CRITICAL

Guidelines

LOW:
Minor inconvenience.
No immediate risk.

MEDIUM:
Moderate disruption affecting a few citizens.

HIGH:
Serious infrastructure damage or significant public inconvenience.

CRITICAL:
Immediate danger to life, emergency services, fire, electrocution,
building collapse, severe flooding, major accidents, etc.

Also provide:

confidence (0-1)

reason (one sentence)

Return ONLY JSON.

Format:

{
"severity_score":8.5,
"severity_label":"HIGH",
"confidence":0.93,
"reason":"Tree fallen across main road causing traffic blockage."
}
"""

In [ ]:
def label_complaint(text):

    response = client.chat.completions.create(
    model="llama-3.1-8b-instant",



        temperature=0,

        response_format={"type": "json_object"},

        messages=[

            {
                "role":"system",
                "content":SYSTEM_PROMPT
            },

            {
                "role":"user",
                "content":text
            }

        ]
    )

    return json.loads(
        response.choices[0].message.content
    )

In [ ]:
sample = df.iloc[0]["text_raw"]

print(sample)

print()

print(label_complaint(sample))

Namaste, for the past three days. We are experiencing garbage pickup has been missed repeatedly. we also tried the IVR earlier. loker madat kara. krupaya sahayya kara.

{'severity_score': 4, 'severity_label': 'MEDIUM', 'confidence': 0.8, 'reason': 'Repeated missed garbage pickup causing moderate inconvenience to residents.'}

In [ ]:
import pandas as pd
from tqdm import tqdm
import time
import json

results = []

In [ ]:
results = []

SAVE_EVERY = 25

for index, row in tqdm(df.iterrows(), total=len(df)):

    complaint = row["text_raw"]

    try:

        output = label_complaint(complaint)

        results.append({

            "complaint_id": row["complaint_id"],
            "complaint": complaint,
            "severity_score": output["severity_score"],
            "severity_label": output["severity_label"],
            "confidence": output["confidence"],
            "reason": output["reason"]

        })

    except Exception as e:

        print(e)

        results.append({

            "complaint_id": row["complaint_id"],
            "complaint": complaint,
            "severity_score": None,
            "severity_label": None,
            "confidence": None,
            "reason": str(e)

        })

    if (index + 1) % SAVE_EVERY == 0:

        pd.DataFrame(results).to_csv(
            "severity_llm_labels.csv",
            index=False
        )

        print(f"Saved till row {index+1}")

  3%|▎         | 25/900 [00:23<42:07,  2.89s/it]

Saved till row 25

  6%|▌         | 50/900 [01:43<46:26,  3.28s/it]

Saved till row 50

  8%|▊         | 75/900 [03:04<44:50,  3.26s/it]

Saved till row 75

 11%|█         | 100/900 [04:25<43:21,  3.25s/it]

Saved till row 100

 14%|█▍        | 125/900 [05:46<43:23,  3.36s/it]

Saved till row 125

 17%|█▋        | 150/900 [07:06<41:20,  3.31s/it]

Saved till row 150

 19%|█▉        | 175/900 [08:27<39:14,  3.25s/it]

Saved till row 175

 22%|██▏       | 200/900 [09:48<38:00,  3.26s/it]

Saved till row 200

 25%|██▌       | 225/900 [11:08<36:36,  3.25s/it]

Saved till row 225

 28%|██▊       | 250/900 [12:29<35:47,  3.30s/it]

Saved till row 250

 31%|███       | 275/900 [13:50<34:02,  3.27s/it]

Saved till row 275

 33%|███▎      | 300/900 [15:11<32:01,  3.20s/it]

Saved till row 300

 36%|███▌      | 325/900 [16:33<33:27,  3.49s/it]

Saved till row 325

 39%|███▉      | 350/900 [17:54<30:15,  3.30s/it]

Saved till row 350

 42%|████▏     | 375/900 [19:15<29:08,  3.33s/it]

Saved till row 375

 44%|████▍     | 400/900 [20:35<27:10,  3.26s/it]

Saved till row 400

 47%|████▋     | 425/900 [21:56<24:33,  3.10s/it]

Saved till row 425

 50%|█████     | 450/900 [23:17<22:23,  2.99s/it]

Saved till row 450

 53%|█████▎    | 475/900 [24:37<22:34,  3.19s/it]

Saved till row 475

 56%|█████▌    | 500/900 [25:59<21:51,  3.28s/it]

Saved till row 500

 58%|█████▊    | 525/900 [27:21<20:35,  3.29s/it]

Saved till row 525

 61%|██████    | 550/900 [28:41<19:18,  3.31s/it]

Saved till row 550

 64%|██████▍   | 575/900 [30:02<17:42,  3.27s/it]

Saved till row 575

 67%|██████▋   | 600/900 [31:23<17:57,  3.59s/it]

Saved till row 600

 69%|██████▉   | 625/900 [32:44<14:58,  3.27s/it]

Saved till row 625

 72%|███████▏  | 650/900 [34:05<13:48,  3.31s/it]

Saved till row 650

 75%|███████▌  | 675/900 [35:26<11:27,  3.05s/it]

Saved till row 675

 78%|███████▊  | 700/900 [36:46<10:50,  3.25s/it]

Saved till row 700

 81%|████████  | 725/900 [38:08<09:32,  3.27s/it]

Saved till row 725

 83%|████████▎ | 750/900 [39:28<07:40,  3.07s/it]

Saved till row 750

 86%|████████▌ | 775/900 [40:51<07:02,  3.38s/it]

Saved till row 775

 89%|████████▉ | 800/900 [42:11<05:29,  3.30s/it]

Saved till row 800

 92%|█████████▏| 825/900 [43:31<03:54,  3.12s/it]

Saved till row 825

 94%|█████████▍| 850/900 [44:51<02:32,  3.05s/it]

Saved till row 850

 97%|█████████▋| 875/900 [46:12<01:20,  3.23s/it]

Saved till row 875

100%|██████████| 900/900 [47:32<00:00,  3.17s/it]

Saved till row 900

In [ ]:
df.to_excel("text_asr_enriched.xlsx", index=False)

In [ ]:
print(df.columns)

Index(['complaint_id', 'text_raw'], dtype='object')

In [ ]:
results[0]

{'complaint_id': 'PGR202500001',
 'complaint': 'Namaste, for the past three days. We are experiencing garbage pickup has been missed repeatedly. we also tried the IVR earlier. loker madat kara. krupaya sahayya kara.',
 'severity_score': 4,
 'severity_label': 'MEDIUM',
 'confidence': 0.8,
 'reason': 'Repeated missed garbage pickup causing moderate inconvenience to residents.'}

In [ ]:
import pandas as pd

# Convert results to DataFrame
results_df = pd.DataFrame(results)

print(results_df.head())

   complaint_id                                          complaint  \
0  PGR202500001  Namaste, for the past three days. We are exper...
1  PGR202500002  Ji, for the past three days. I am reporting th...
2  PGR202500003  Good evening, for 48 hours. We are experiencin...
3  PGR202500004  Good evening, since last night. an old buildin...
4  PGR202500005  Hi, for the past three days. We are experienci...

   severity_score severity_label  confidence  \
0             4.0         MEDIUM        0.80
1             4.0         MEDIUM        0.80
2             6.0         MEDIUM        0.85
3             8.0           HIGH        0.85
4             8.0           HIGH        0.95

                                              reason
0  Repeated missed garbage pickup causing moderat...
1  Repeated missed garbage pickup causing inconve...
2  Residents are experiencing a 48-hour water out...
3  Cracked wall in an old building poses a risk o...
4  Septic tank overflow onto the street, causing ...

In [ ]:
enriched_df = df.merge(
    results_df[
        [
            "complaint_id",
            "severity_score",
            "severity_label",
            "confidence",
            "reason"
        ]
    ],
    on="complaint_id",
    how="left"
)

In [ ]:
print(enriched_df.head())
print(enriched_df.columns)

   complaint_id                                           text_raw  \
0  PGR202500001  Namaste, for the past three days. We are exper...
1  PGR202500002  Ji, for the past three days. I am reporting th...
2  PGR202500003  Good evening, for 48 hours. We are experiencin...
3  PGR202500004  Good evening, since last night. an old buildin...
4  PGR202500005  Hi, for the past three days. We are experienci...

   severity_score severity_label  confidence  \
0             4.0         MEDIUM        0.80
1             4.0         MEDIUM        0.80
2             6.0         MEDIUM        0.85
3             8.0           HIGH        0.85
4             8.0           HIGH        0.95

                                              reason
0  Repeated missed garbage pickup causing moderat...
1  Repeated missed garbage pickup causing inconve...
2  Residents are experiencing a 48-hour water out...
3  Cracked wall in an old building poses a risk o...
4  Septic tank overflow onto the street, causing ...
Index(['complaint_id', 'text_raw', 'severity_score', 'severity_label',
       'confidence', 'reason'],
      dtype='object')

In [ ]:
enriched_df.to_excel("text_asr_enriched_82percent.xlsx", index=False)

from google.colab import files
files.download("text_asr_enriched_82percent.xlsx")

In [ ]:
!pip install sentence-transformers catboost scikit-learn joblib

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.23.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 5.0 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [ ]:
import pandas as pd

df = pd.read_excel("text_asr_enriched.xlsx")

df.head()

,complaint_id,text_raw,severity_score,severity_label,confidence,reason
0,PGR202500001,"Namaste, for the past three days. We are exper...",4.0,MEDIUM,0.80,Repeated missed garbage pickup causing moderat...
1,PGR202500002,"Ji, for the past three days. I am reporting th...",4.0,MEDIUM,0.80,Repeated missed garbage pickup causing inconve...
2,PGR202500003,"Good evening, for 48 hours. We are experiencin...",6.0,MEDIUM,0.85,Residents are experiencing a 48-hour water out...
3,PGR202500004,"Good evening, since last night. an old buildin...",8.0,HIGH,0.85,Cracked wall in an old building poses a risk o...
4,PGR202500005,"Hi, for the past three days. We are experienci...",8.0,HIGH,0.95,"Septic tank overflow onto the street, causing ..."

In [ ]:
df = df.dropna(subset=["severity_score"])

print(len(df))

744

In [ ]:
X = df["text_raw"].astype(str)

y = df["severity_score"].astype(float)

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

X_embeddings = model.encode(
    X.tolist(),
    show_progress_bar=True
)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/24 [00:00<?, ?it/s]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_embeddings,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from catboost import CatBoostRegressor

cat = CatBoostRegressor(
    iterations=500,
    depth=6,
    learning_rate=0.05,
    loss_function="RMSE",
    verbose=100,
    random_seed=42
)

cat.fit(
    X_train,
    y_train
)

0:	learn: 2.3516819	total: 824ms	remaining: 6m 51s
100:	learn: 0.8197675	total: 23s	remaining: 1m 30s
200:	learn: 0.4689540	total: 34.5s	remaining: 51.3s
300:	learn: 0.3102033	total: 45.6s	remaining: 30.1s
400:	learn: 0.2270210	total: 56.6s	remaining: 14s
499:	learn: 0.1583678	total: 1m 6s	remaining: 0us

CatBoostRegressor(depth=6, iterations=500, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=100)

In [ ]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

pred = cat.predict(X_test)

print("MAE :", mean_absolute_error(y_test,pred))
print("RMSE:", mean_squared_error(y_test,pred)**0.5)
print("R² :", r2_score(y_test,pred))

MAE : 1.0168905113329763
RMSE: 1.3687507834303216
R² : 0.7320163740849837

In [ ]:
import joblib

cat.save_model("severity_model.cbm")

joblib.dump(model,"sentence_transformer.pkl")

['sentence_transformer.pkl']